/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package engtelecom.poo;

import java.util.Scanner;

public class App {


    public static void main(String[] args) {

        Scanner linha = new Scanner(System.in);
        int count = 1;

        while (linha.hasNext()){

            String aux = linha.nextLine();


            System.out.print(count + " ");
            System.out.println(aux.toUpperCase());
            count++;

        }

    }
}

