/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package engtelecom.poo;

/**
 * Aula de javaDOC
 */
public class App {
    /**
     * Classe App
     */
    public App() {
    }

    /**
     * Metodo principal
     *
     * @param args args
     */
    public static void main(String[] args) {

        // Documentação com JavaDOC
        // teste de unidade

        /**
         * Objeto
         */
        Carro c = new Carro();

        c.acelerar(10);

        System.out.println();


    }
}
