/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package engtelecom.poo;

import java.time.LocalDate;
import java.util.ArrayList;

public class App {

    private ArrayList<Tarefa> listaTarefa;
    private ArrayList<Grupo> listaGrupo;

    public App() {
        this.listaTarefa = new ArrayList<>();
        this.listaGrupo = new ArrayList<>();
    }

    public static void main(String[] args) {

        App app = new App();



        // Criar tarefa
        Tarefa tarefa = new Tarefa("tarefa 1", LocalDate.of(2024,06,06),LocalDate.of(2024,01,06),new Pessoa("Wagner"), new Grupo("POO"));

    }
}
