/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package engtelecom.poo;

import java.util.Random;

public class App {

    public static void main(String[] args) {
        // Variáveis
        int tamanho = 9, bombas = 10;

        // Criar uma Matriz de String 10 x 10
        String[][] campo = new String[tamanho][tamanho];

        // Obtendo números pseudo aleatórios
        Random r = new Random();

        // Laço que cria a matriz de string de tamanho  n x n preenchida com  "."
        for(int i=0; i < tamanho; i++){
            for(int j=0; j < tamanho; j++){
                campo[i][j] = ".";
            }
        }
        // Laço que sorteia uma liha de cada coluna até completar a quantidade de bombas
        int k = 0;
        while ( k < bombas){
            int linha = r.nextInt(tamanho);
            int coluna = r.nextInt(tamanho);
            k++;
            if(campo[linha][coluna].equals("*")){
                k--;
            } else {
                campo[linha][coluna] = "*";
            }
        }
        // Laço para imprimir na tela a matriz resultantye
        for(int i=0; i < tamanho; i++){
            for(int j=0; j < tamanho; j++){
                System.out.print(campo[i][j]+ "");
            }
            System.out.println("");

        }
    }

}
