/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package engtelecom.poo;

public class App {


    public static void main(String[] args) {

        
        // Classe Carro
        Carro c = new Carro();
        Carro b = new Carro();
        System.out.println("Classe Carro:");
        System.out.println("Velociadde c: " + c.obterVelocidade());
        c.acelerar(10);
        System.out.println("Velociadde c: " + c.obterVelocidade());
        System.out.println("Velociadde d: " + b.obterVelocidade());
        System.out.println();


        //Classe Contador
        Contador a = new Contador();
        System.out.println("Classe Contador: ");
        a.atribuir(5);
        System.out.println("Contagem atual: " + a.obter());
        a.incrementar();
        System.out.println("Contagem atual: " + a.obter());
        System.out.println();


        //Classe Buzz
        Buzz d = new Buzz();
        System.out.println("Classe Buzz: ");
        d.disparaLaser(false);
        d.abreAsas(true);
        d.bracoArticulado(false);
        d.falarFrase();
        d.capaceteRetratil(true);








    }
}
