/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package engtelecom.poo;

public class App {


    public static void main(String[] args) {

        Carro fusca = new Carro(100);

        fusca.getVelocidadeAtual();

        Carro.aceleracao();

        Math.pow(2,2);
        Math.random();


        /*
        // Classe Carro
        Carro c = new Carro();
        Carro b = new Carro();
        System.out.println("Classe Carro:");
        System.out.println("Velociadde c: " + c.obterVelocidade());
        c.acelerar(10);
        System.out.println("Velociadde c: " + c.obterVelocidade());
        System.out.println("Velociadde d: " + b.obterVelocidade());
        System.out.println();


        //Classe Contador
        Contador a = new Contador();
        System.out.println("Classe Contador: ");
        a.atribuir(5);
        System.out.println("Contagem atual: " + a.obter());
        a.incrementar();
        System.out.println("Contagem atual: " + a.obter());
        System.out.println();


        //Classe Buzz
        System.out.println("Classe Buzz: ");
        Buzz d = new Buzz();
        d.disparaLaser();
        d.falarFrase();
        d.golpear();
        d.capaceteRetratil();
        System.out.println();

        // Classe Caneta
        System.out.println("Classe Caneta: ");

        Caneta bic = new Caneta();
        bic.definirCor("azul");
        bic.definirNivelTinta((3));

        Caneta pilot = new Caneta();
        bic.definirCor("vermelha");
        bic.definirNivelTinta((1));

        bic.abrirFechar();
        bic.desenhar();

        pilot.desenhar();
        */

        // Classe Pessoa
/*
        Pessoa[] vetor = new Pessoa[10];


        Pessoa juca = new Pessoa();
        Pessoa ana = new Pessoa();


        vetor[0].setNome("Wagner");
        vetor[0].setCpf("96571756072");
        vetor[0].setSexo("M");
        vetor[0].setEmail("wapa@wapa.com.br");
        vetor[0].setEndereco("Floripa");
        vetor[0].setTelefone("48 999815336");

        ana.setNome("Ana");
        ana.setCpf("efnD~LKVNJ~KLE");
        ana.setSexo("F");
        ana.setEmail("ana@ana");
        ana.setEndereco("Sao Jose");
        ana.setTelefone("48 çdksjfnDNVDK");

        vetor[1] = ana;

        for (int i = 0; i < vetor.length; i++) {
            for (Pessoa p : vetor) {
                System.out.println(p + "\n");
            }
        }

 */


    }
}

