/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package engtelecom.poo;

public class App {

    public static void main(String[] args) {

        Horario a = new Horario(24,59,59);
        Horario b = new Horario(2,59,10);

        System.out.println(a);
        System.out.println(a.horarioPorExtenso());
        System.out.println(a.horarioEmSegundos());
        System.out.println(a.diferencaSegundos(b));

    }
}
