/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package engtelecom.poo;

public class App {

    public static void main(String[] args) {

    Pilha<String> pilha = new Pilha<>(4);

        try {
            pilha.empilhar("Prato");
            pilha.empilhar("Panela");
            pilha.empilhar("Garfo");
            pilha.empilhar("Faca");

        } catch (PilhaCheiaException e) {
            throw new RuntimeException(e);
        }

        System.out.printf(pilha.obterElementoTop());


        try {
            pilha.dsempilhar();
        } catch (PilhaVaziaExeception e) {
            throw new RuntimeException(e);
        }


        System.out.printf(pilha.obterElementoTop());





    }
}
