/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package engtelecom.poo;

import edu.princeton.cs.algs4.Draw;

import java.awt.*;

public class App {

    public static void main(String[] args) {

        Draw draw = new Draw();

        //draw.clear(Color.LIGHT_GRAY);
        //draw.setPenColor(Color.BLUE);

        //draw.setPenRadius(.3);

        //draw.line(.8,.8,.5,.5);
        //draw.rectangle(.5,.5,100,100);

        //draw.filledSquare(.5,.5,.1);

        //draw.text(.5,.5,"Olá Mundo");

        draw.setCanvasSize(800,800);
        draw.setXscale(0,800);
        draw.setYscale(0,800);

        //draw.setPenColor(Color.BLUE);

       // draw.filledSquare(100,100,50);

        draw.picture(400,400,"duke.jpg");




    }
}
