/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package engtelecom.poo;

import engtelecom.poo.produto.SemFio;
import engtelecom.poo.produto.Telefone;

public class App {


     public static void main(String[] args) {

         Telefone t = new Telefone(01,"010101","tele", "branco", 10);

         SemFio s = new SemFio(02,"0202020", "sem", "preto",20,900,3,100);

         System.out.println(t.imprimirDados());

         System.out.println(s.imprimirDados());

         System.out.println(t.imprimirDados());



    }
}
