/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package engtelecom.poo;

public class App {

    public static void main(String[] args) {

        Retangulo r = new Retangulo(20,10,"ASCI");

        System.out.println(r);
        System.out.println(r.perimetroRetangulo());
        System.out.println(r.areaRetangulo());


    }
}
