/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package engtelecom.poo;

import java.math.MathContext;

import java.util.Random;

public class App {

    public static void main(String[] args) {

        // Criando as variáveis e tranformando de String para Double
        Double valorDiario = Double.parseDouble(args[0]);
        Double metaDiaria = Double.parseDouble(args[1]);
        Double numeroDias = Double.parseDouble(args[2]);

        // verifica se foram informadas os 03 argumentos e valores mínimos
        if ((args.length != 3) || (valorDiario < 1.01) || (metaDiaria < 0.01) || (numeroDias < 1)) {
            System.out.println("Argumentos inválidos, preencha: Valor diário (>R$ 0,00), meta diária (>R$ 0,00), numero de dias (>0)");
        } else {
            System.out.println("Forneceu " + args.length + " Argumentos");
            System.out.println("Valor diário: " + valorDiario);
            System.out.println("Meta diária: " + metaDiaria);
            System.out.println("Número de dias: " + numeroDias);
        }
        // Variavel para medir quantos dias atingiu a meta
        int contDias = 0;
        // Variavel para medir numero de apostas realizadas
        int apostas = 0;
        // loop para contabilizar numero de dias que estipipulou que jogaria
        while (numeroDias > 0){
            // carregando variaveis com o valor original do arqumento para iniciar a cada dia
            valorDiario = Double.parseDouble(args[0]);
            metaDiaria = Double.parseDouble(args[1]);
            // loop para validar a condição de meta diaria e valor diário
             while ((metaDiaria > valorDiario) && (valorDiario > 1)) {
                 // Obtendo números pseudo aleatórios para a roleta de 0 a 36
                 Random r = new Random();
                 int roleta = r.nextInt(37);
                 // condicional para ver se o número é impar ou par
                 if (roleta % 2 == 0) {
                      // é par
                      valorDiario--;
                 } else {
                      //é impar
                      valorDiario++;
                   }
                 apostas ++;
             }
             numeroDias --;
             // condicional para contabilizar se bateu a meta no dia
             if (valorDiario >= metaDiaria){
                 contDias ++;
             }
        }
        // atualizando o numero do dias com os argumentos para contabilizar o resultado
        numeroDias = Double.parseDouble(args[2]);
        System.out.println("O jogador atingiu sua meta em " + contDias + " dos " + Math.round(numeroDias) + ", dias que foi ao estabelecimentos, ou seja, ganhou em " + Math.round((contDias/numeroDias)*100) + "% das vezes. O número médio de apostas foi " + (apostas/contDias) +" por dia." );
    }
}
