/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package engtelecom.poo;

import org.checkerframework.checker.units.qual.A;

import java.time.LocalDate;
import java.util.ArrayList;
import java.util.Arrays;

public class App {

    private ArrayList<Livro> livros;
    private ArrayList<Autor> autores;

    private Carro carro;
    private ArrayList<Motor> motores;



    public App() {
        this.livros = new ArrayList<>();
        this.autores = new ArrayList<>();

        this.carro = new Carro("fusca",new Motor("500", "100"),"preto");

        this.motores = new ArrayList<>();
    }

    public void trocaMotor(Motor m){
        this.motores.add(this.carro.getMotor());
        this.carro.setMotor(m);
    }

    public void trocaCarro(Carro c){
        this.carro = c;
    }

    public boolean addAutor(Autor autor){
        return  this.autores.add(autor);
    }

    public boolean addLivro(String isbn, String titulo, Autor[] autores){
        ArrayList<Autor> aux = new ArrayList<>(Arrays.asList(autores));
        return this.livros.add((new Livro(isbn,titulo,aux)));
    }

    public static void main(String[] args) {

        App app = new App();




/*
        Motor motor = new Motor("500","100");
        Carro carro = new Carro("fusca",motor, "preto");

        System.out.println(carro);


        app.trocaMotor(new Motor("200", "80"));

        app.trocaCarro(new Carro("porsche",new Motor("1000", "300"), "vermelha"));

        System.out.println(app.carro);


*/

        /*
        app.addAutor(new Autor("Juca", "BRA", LocalDate.of(200,02,02)));

        app.addLivro("15y149512948", "Livro 1", new Autor[]{app.autores.getFirst()} );


    Livro livro;
    Livro livro2;

    ArrayList<Autor> autores = new ArrayList<>();

    Autor juca = new Autor("Juca", "BRA", LocalDate.of(1980,10,01));
    Autor ana = new Autor("Ana","BRA", LocalDate.of(1990,10,01));
    Autor pedro = new Autor("Pedro", "BRA", LocalDate.of(1981,06,06));


    autores.add(juca);
    autores.add(ana);


    livro = new Livro("102434580", "Pequeno Principe", autores);
    System.out.println(livro);

    ArrayList<Autor> autores2 = new ArrayList<>();

    autores2.add(juca);
    autores2.add(pedro);


    livro2 = new Livro("102rlgjqirjgq0", "~SHGJGGND", autores2);
    System.out.println(livro2);

    // Banco de dados de Autores e outro de Livros

*/
    }
}
